#!/bin/sh
env
#echo "Setting env vars"
#cd
#cat profile
#cat environment.yml
#port=$(awk '/PORT_REDIS/ {print $2;}' environment.yml)
#echo $port
#sed -e "s|{port}|$port|" redis.conf.in1 > redis.conf.in2
#sed -e "s|{password}|${REDISPASS}|" redis.conf.in2 > redis.conf
#echo "for debugging"
#cat redis.conf